[package]
name = "gelf_logger"
version = "0.1.0"
authors = ["OVH SAS <github@ovh.net>"]
edition = "2018"

[features]
ovh-ldp = ["serde_gelf/ovh-ldp"]

[dependencies]
log = { version = "0.4", features = ["std"] }
native-tls = "0.2"
serde = "1.0"
serde-value = "0.5"
serde_derive = "1.0"
serde_gelf = {git = "https://github.com/ovh/serde_gelf"}
serde_json = "1.0"
serde_yaml = "0.8"
