[package]
name = "gelf_logger"
version = "0.1.0"
authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]
edition = "2018"

[features]
ovh-ldp = []

[dependencies]
log = { version = "0.4", features = ["std"] }
serde = "1.0"
serde-value = "0.5"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
serde_gelf = {git = "https://github.com/cdumay/serde_gelf", features = ["ovh-ldp"]  }

[[example]]
name = "ldp"
path = "examples/ldp.rs"